name: resgate_client
description: A client for Resgate.
version: 1.0.1

environment:
  sdk: ^3.5.3

dependencies:
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.14
