name: resgate_client
description: A client for Resgate.
version: 1.0.0

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
